version: '3'

services:
  websocket-server:
    image: consolews
    command: npm run start:wsstart
    ports:
      - "8080:8080"
    container_name: Websocket-events

  db:
    image: mariadb:10.3
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD="root"
    - MYSQL_DATABASE="botdiscord"
    - MYSQL_PASSWORD="root"
    - MYSQL_USER="botdiscord"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - saturn

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - saturn
    container_name: phpmyadmin
    

  saturn:
    build: 
      context: .
    links:
      - db
      - websocket-server
    depends_on:
      - db
      - websocket-server
    networks:
      - saturn
    container_name: Botdiscord
    restart: always

volumes:
  dbdata:

networks:
  saturn:
